--- #stop service light environment
- hosts: all
  connection: local
  #sudo: true
  #remote_user: jboss
  tasks:
  - name: echo test
    remote_user: jboss
    command: whoami
    register: whoami_output
  - debug: var=whoami_output.stdout
  - name:  SPLUNK STOP
    service: name=splunk state=stopped
    #become: true
    #become_user: jboss
    #notify:
    #- stop splunk
  #handlers:
  #- name: stop splunk
    #service: name=splunk state=stopped
  - name: JENKINS STOP
    service: name=jenkins state=stopped
    #become: true
    #become_user: jboss
