--- #stop service light environment
- hosts: all
  #connection: local
  #sudo: true
  tasks:
  - name:  SPLUNK STOP
    service: name=splunk state=stopped
    become: true
    #notify:
    #- stop splunk
  #handlers:
  #- name: stop splunk
    #service: name=splunk state=stopped
  - name: JENKINS STOP
    service: name=jenkins state=stopped
    become: true
